# Generated by Django 5.2.3 on 2025-07-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
