# Generated by Django 5.2.3 on 2025-07-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0002_user_experience_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experience_years',
        ),
    ]
