# Generated by Django 5.2.3 on 2025-07-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0005_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
