# Generated by Django 5.2.8 on 2025-11-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0006_remove_user_picture_url_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='farm_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='farm_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('producer', 'Producer'), ('consumer', 'Consumer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
