# Generated by Django 5.2.8 on 2025-11-07 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/main/')),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('long_description', models.TextField(blank=True)),
                ('unit_type', models.CharField(choices=[('unit', 'Par unité'), ('kg', 'Au kilo')], default='unit', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_available', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location_village', models.CharField(blank=True, max_length=255)),
                ('location_commune', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10)),
                ('file', models.FileField(upload_to='products/medias/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='app_products.product')),
            ],
            options={
                'verbose_name': 'Média du produit',
                'verbose_name_plural': 'Médias du produit',
            },
        ),
    ]
